### PR TITLE
GsonReader: Rethrow exceptions as Gson types

### LINKED ISSUE #1: The Gson module should re-throw `ParseException` as Gson exceptions
This affects the `gson` module only, since gson clients will be expecting to catch the Gson exceptions rather than the quilt-parser exceptions.

I think this means we need to do the mapping:

- `ParseException` -> `JsonParseException` (although it's not thrown directly, so this is less important)
- `MalformedSyntaxException` -> `JsonSyntaxException`
- `FormatViolationException` -> `JsonSyntaxException` (although it doesn't seem to be thrown)

### PR DESCRIPTION
**Pull request by Leo40Git**
Closes QuiltMC#1.

### CODE REVIEW

**Review by eristhea — COMMENTED** [review]
looks great!
I'd probably pull error handling into a `void rethrowJsonExceptions(Runnable)` just to cut down on LOC a bit

**Comment by Leo40Git** [comment]
> looks great! I'd probably pull error handling into a `void rethrowJsonExceptions(Runnable)` just to cut down on LOC a bit

me: yeah I should do that
also me: makes 5 separate methods for that to cover all the possible return types because Java generics are a lie

**Review by OroArmor — APPROVED** [review]

**Review by AlexIIL — CHANGES_REQUESTED** [review]
The performance gains by using per-type functions are unlikely to be worth the added maintenance cost of having 6 separate functions instead of a single one, please instead use `DelegateFunction` instead. (In addition creating a lambda invoker creates an object too - `delegate::beginArray` needs to store the `delegate` in a new object that implements `DelegateAction`)

For the `void` variant though you'll need to declare a second type that extends the first, like:

```java
@FunctionalInterface
private interface DelegateAction extends DelegateFunction<Void> {
    @Override
    Void call() throws IOException {
        run();
        return null;
    }

    void run() throws IOException;
}

private void rethrowGsonExceptions(DelegateAction action) throws IOException {
    rethrowGsonExceptions((DelegateFunction<Void>) action);
}
```

As that way we can keep all the exception handling in one place?
(Alternatively you could call it `rethrowGsonExceptionsVoid` instead, to avoid the casting to select the right method).

**Review by AlexIIL — APPROVED** [review]
Looks good, thanks!

**Review by TheGlitch76 — APPROVED** [review]

**Pull request merged**
